In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
uploaded = files.upload()
import io
df = pd.read_csv(io.BytesIO(uploaded['Entity_Type_Detector_Data_Set.csv']))

Saving Entity_Type_Detector_Data_Set.csv to Entity_Type_Detector_Data_Set (1).csv

In [ ]:
from google.colab import files
uploaded = files.upload()
import io
df5 = pd.read_csv(io.BytesIO(uploaded['main_city.csv']))

Saving main_city.csv to main_city (3).csv

In [ ]:
from google.colab import files
uploaded = files.upload()
import io
df4 = pd.read_csv(io.BytesIO(uploaded['names.csv']))

Saving names.csv to names.csv

In [ ]:
df_names=df4["Forename"]

In [ ]:
name_list = df_names.tolist()

In [ ]:
name_list[0:10]

['Maria ',
 'Nushi ',
 'Mohammed',
 'Jose',
 'Muhammad',
 'Mohamed',
 'Wei',
 'Mohammad',
 'Ahmed',
 'Yan']

In [ ]:
list1 = ["Michael", "Ali", "David", "Mohamed", "John", "Mohammed", "Ahmed","Abdul", "Thomas", "Juan", "James","Joseph","Carlos",
         "Abdullah", "Antonio", "Robert", "Richard", "Peter", "王", "李", "张", "刘", "陈",
         "杨", "黄", "赵", "مُ", "Emma", "Maria", "Nushi", "Jose", "Wei", "Yan", "Li" , "Smith", 
         "Ana", "Ying", "Juan", "Anna","Mary" "Jean", "Robert", "Daniel" , "Luis", 
         "Carlos", "James", "Antonio", "Joseph", "Hui", "Elena", "Francisco","Hong"
         "Marie", "Min ", "Lei" ,"Yu","Ibrahim", "Peter", "Fatima", "Aleksandr", 
         "Richard", "Xin", "Ping","Paul", "Lin ", "Olga", "Sri", "Pedro", "William", "Rosa", "Thomas", 
         "Jorge", "Yong", "Elizabeth", "Sergey", "Ram", "Patricia", "Hassan", "Anita","Manuel","Victor", "Sandra",
         "Ming", "沐宸", "浩宇", "沐辰", "茗泽", "奕辰", "宇泽", "浩然", "奕泽","宇轩", "沐阳", 
         "若汐", "一诺", "艺涵","依诺", "梓涵", "苡沫", "雨桐", "欣怡", "语桐", "语汐" ,"Hossain","佐藤", "鈴木","高橋"
         "田中", "渡辺", "伊藤","中村", "小林", "山本", "加藤" , "吉田", "山田", "山口","松本", "	井上", "木村", "清水", "林",
         "斉藤", "斎藤", "山崎", "中島", "森"	, "阿部", "池田", "橋本", "石川", "	山下", "小川", "石井", "後藤", "岡田",
         "Smith", "Johnson", "Williams", "Brown", "Jones", "Miller","Davis", "Garcia" , "Rodriguez"
        "Wilson", "Martinez", "Anderson", "Taylor","Thomas", "Hernandez", "Moore", "Martin", "Jackson", "Thompson", "Lopez", "Lee", "Gonzalez", 
        "Harris", "Lewis", "Robinson", "Perez", "José", "María", "Marry", "Lucía", "Sofía", "Martina"
        "Paula", "Lucas", "Hugo", "Martín", "Daniel", "Pablo", "ария","Маша" , "Анна", "Аня", "Виктория", "Вика", "Ольга" ,"Оля", 
         "Наталья", "Наташа", "Татьяна" "Таня","Иван" "Ваня", "Дмитрий" "Дима", "Пётр","Владимир" ,"Николай", "Коля", "Антон", "Андрей", 
         "Krishna", "Shiva", "Narayan", "Piyush", "Vishwajeet", "Arjuna", "Hariom", "Karan", "Pavan", "Aditya", "Vihaan", "Pranav", "Rithvik", "Aarush",
         "حسن", "مُحَمَّد", "بن", "محمد", "خالد", "عبدالله","أحمد", "فهد","سلمان", "سعود	" ,"Mr", "Jr", "Mrs","Esq","Phd", "先生", 'Ali','Ali','John','David','Li','Abdul','Ana','Ying','Michael',
         'Juan','Anna','Mary','Jean','Robert','Daniel','Luis','Carlos','James','Antonio','Joseph']

In [ ]:
final_name_list=list1+name_list

In [ ]:
final_name_list[0:10]

['Michael',
 'Ali',
 'David',
 'Mohamed',
 'John',
 'Mohammed',
 'Ahmed',
 'Abdul',
 'Thomas',
 'Juan']

In [ ]:
df['has_common_person_name'] = df['Entity Name'].apply(lambda x:  1 if any(substring in x for substring in final_name_list) else 0)

In [ ]:
df['has_common_person_name'].value_counts()

0    5932
1    4067
Name: has_common_person_name, dtype: int64

In [ ]:
common_name = (df["has_common_person_name"] == 1)
df_common_name  = df[common_name]
df_common_name.sample(10)

,Entity Name,Entity Type,has_common_person_name
308,École Nationale d'Administration et de Magistr...,Company,1
9459,Ashraf Ariff Abdul Razak,Person,1
8274,"Ostroushko, Valentina Viktorovna",Person,1
9803,"Al-Abdali, Issa Saleh Saif",Person,1
9001,陈啟兵,Person,1
4330,"Di Ruzza, Marco",Person,1
7028,Narantuya Balaasuren,Person,1
1503,Jordan Steel Company PSC,Company,1
2372,Kumul Petroleum Holdings,Company,1
9129,"al Mahfali, Omar Mohsen",Person,1

In [ ]:
test= ((df["has_common_person_name"] == 1)&(df['Entity Type']))
df_test  = df[test]
df_test.sample(10)

False    6851
True     3148
dtype: int64

In [ ]:
df5

          city_ascii
0              Tokyo
1            Jakarta
2              Delhi
3             Manila
4          Sao Paulo
...              ...
4439           ماكاو
4440       جزر فاروس
4441   الأرض الخضراء
4442  غيانا الفرنسية
4443         جوادلوب

[4444 rows x 1 columns]

In [ ]:
df_city2=df5["city_ascii"]

0                Tokyo
1              Jakarta
2                Delhi
3               Manila
4            Sao Paulo
             ...
3573             _____
3574         ___ _____
3575     _____ _______
3576    _____ ________
3577           _______
Name: city_ascii, Length: 3578, dtype: object

In [ ]:
df_city2=df5["city_ascii"]
ty_list2 = df_city2.tolist()
city_list2[0:10]

NameError: ignored

In [ ]:
df['has_city_list2'] = df['Entity Name'].apply(lambda x:  1 if any(substring in x for substring in city_list2) else 0)

In [ ]:
df['has_city_list2'].value_counts()

0    9278
1     721
Name: has_city_list2, dtype: int64

In [ ]:
location_name = (df["has_city_list2"] == 1)
df_location_name = df[location_name]
df_location_name.sample(40)

,Entity Name,Entity Type,has_city_list2
1020,Eni Gabon S.A.,Company,1
1457,Jamaica Vacations,Company,1
2950,National Taiwan University of Science and Tech...,Company,1
898,ALBA Alimentos de El Salvador,Company,1
3204,Scotiabank Uruguay S.A.,Company,1
2797,Airports Company South Africa,Company,1
828,Polyplas Dominicana - Grupo Diesco,Company,1
1239,Kingstronic (Hong Kong),Company,1
2588,Africa Improved Foods Rwanda,Company,1
3790,Industriji Elettroniċi Iran,Company,1
3077,Institute of History of Academy of Sciences of...,Company,1
232,Bangladesh Municipal Development Fund,Company,1
1502,Jordan Insurance Company P.L.C,Company,1
581,Trichem de Colombia S.A.,Company,1
6064,Mario Salvador Pérez Fleites,Person,1
1655,Telia Carrier Latvia SIA,Company,1
1030,"Georgian Gas Transportation Company, LLC",Company,1
1592,Kuwait Industrial Projects Company,Company,1
9709,"Tobii, Richmond Nagbe",Person,1
8864,"Papakokkinos-Van Heyste, Georgia",Person,1
71,Angola Telecom E.P.,Company,1
1414,Bank Leumi Le-Israel Ltd.,Company,1
2557,VFS Int Romania Leasing Operational,Company,1
3139,Dniprometalservis,Company,1
2412,Caja Municipal de Ahorro y Crédito de Trujillo,Company,1
3314,Frontier Operations Zambia,Company,1
1403,Cross Israel Highway Ltd.,Company,1
3119,Uganda Broadcasting Corporation,Company,1
2103,B&E International (Namibia),Company,1
1008,DAVUM Gabon,Company,1
2040,Dil Commerce d.o.o. Podgorica,Company,1
5147,"Housewright, Leonard Stanley",Person,1
3123,Muks Uganda Ltd.,Company,1
5028,"Norville, Sydney",Person,1
1160,YTL (Guernsey) Limited,Company,1
2992,Dushanbekommunservice,Company,1
2504,Beltone Financial Qatar LLC,Company,1
606,Scotiabank de Costa Rica,Company,1
7810,"Permana, Dede Indra",Person,1
9754,"Martin, Berney",Person,1

In [ ]:
df_names=df5["location"]
df_names

KeyError: ignored

In [ ]:
name_list = df_names.tolist()

In [ ]:
name_list[10:30]

['Ali',
 'John',
 'David',
 'Li',
 'Abdul',
 'Ana',
 'Ying',
 'Michael',
 'Juan',
 'Anna',
 'Mary',
 'Jean',
 'Robert',
 'Daniel',
 'Luis',
 'Carlos',
 'James',
 'Antonio',
 'Joseph',
 'Hui']

In [ ]:
df['has_common_name'] = df['Entity Name'].apply(lambda x:  1 if any(substring in x for substring in name_list) else 0)

In [ ]:
df['has_common_name'].value_counts()

0    5458
1    4541
Name: has_common_name, dtype: int64

In [ ]:
common_name = (df["has_common_name"] == 1)
df_common_name = df[common_name]
df_common_name.sample(10)
#losts of error

,Entity Name,Entity Type,has_place_name,has_common_person_name,has_common_name,has_prefix/suffix
4832,Pascal AMBROSI,Person,0,1,1,1
5719,"Singh, Malvinder Mohan",Person,0,1,1,1
2130,Rasuwagadhi Hydropower Company Limited,Company,0,0,1,1
2857,Ceybank Asset Management,Company,1,1,1,1
432,Richpoint Company Limited,Company,0,0,1,1
8967,"FRYČ,Antonín",Person,0,1,1,1
3145,Ukrviyskkurort at the Ministry of Defence of U...,Company,0,1,1,1
6466,Claude Marx,Person,0,1,1,1
9947,Thongdy Phabboua-On,Person,0,1,1,1
4259,ARROW公司,Company,0,1,1,1

In [ ]:
from google.colab import files
uploaded = files.upload()
import io
df3 = pd.read_csv(io.BytesIO(uploaded['worldcities.csv']))

NameError: ignored

In [ ]:
df3

                      city_ascii
0                          Tokyo
1                        Jakarta
2                          Delhi
3                         Manila
4                      Sao Paulo
...                          ...
20841                Chestermere
20842                Painesville
20843                  Poperinge
20844  Santo Amaro da Imperatriz
20845                 Jaggampeta

[20846 rows x 1 columns]

In [ ]:
df.shape

(9999, 3)

In [ ]:
df_city=df3["city_ascii"]
df_city

0                            Tokyo
1                          Jakarta
2                            Delhi
3                           Manila
4                        Sao Paulo
                   ...
20841                  Chestermere
20842                  Painesville
20843                    Poperinge
20844    Santo Amaro da Imperatriz
20845                   Jaggampeta
Name: city_ascii, Length: 20846, dtype: object

In [ ]:
city_list = df_city.tolist()
city_list[0:10]

['Tokyo',
 'Jakarta',
 'Delhi',
 'Manila',
 'Sao Paulo',
 'Seoul',
 'Mumbai',
 'Shanghai',
 'Mexico City',
 'Guangzhou']

In [ ]:
df['has_place_name'] = df['Entity Name'].apply(lambda x:  1 if any(substring in x for substring in city_list) else 0)

In [ ]:
df['has_place_name'].value_counts()

0    6842
1    3157
Name: has_place_name, dtype: int64

In [ ]:
palce_name = (df["has_place_name"] == 1)
df_palce_name = df[palce_name]
df_palce_name.sample(30)

,Entity Name,Entity Type,has_place_name
7593,Querubina Melodasilva,Person,1
1860,Reserve Bank of Malawi,Company,1
8711,José Maria de Mello São Payo Brandão de Brito,Person,1
4452,Mahamat Bachar Gadaya,Person,1
2992,Dushanbekommunservice,Company,1
3065,Optimum Otomotiv Satiş Sonrasi Çözümleri,Company,1
8652,María Adelaida Tamayo Jaramillo,Person,1
4818,Roy Hudson,Person,1
9389,"Sana, Aminata",Person,1
482,La Banque Internationale du Cameroun pour l’Ep...,Company,1
3272,Mantenimiento y Suministros Maferpa C. A.,Company,1
4537,"Drozdov, Georgiy Yevgenyevich",Person,1
5256,Rashied Baderoen,Person,1
9193,"Bayard, Benoit",Person,1
2672,Société d'Aménagement et de Promotion des Côte...,Company,1
1819,Sava Station dooel Skopje,Company,1
8255,Kenneth Jefferson,Person,1
1598,Ibn Sina Hospital,Company,1
319,Université de Parakou,Company,1
9028,Poul Weihrauch,Person,1
2005,Mongolian Securities Clearing House and Centra...,Company,1
6162,Sam Bockarie,Person,1
9922,Mandy Ng,Person,1
2015,Mongolian Mining,Company,1
4781,"Almakhas, Taleb Mohammed Kulaifikh Tweem",Person,1
904,Tallinna Sojus,Company,1
2932,Syrian Computer Society,Company,1
8646,Tamara Bopp-Du-Pont,Person,1
5544,"Malipon, Poomipak",Person,1
2168,Braemar Lodge 2004 Limited,Company,1

In [ ]:
df

                                            Entity Name Entity Type
0            Habib Afghan Road and Construction Company     Company
1                             Aziz Construction Company     Company
2                                     Musawir Najib Ltd     Company
3                               Bamyan Central Hospital     Company
4     Sadat Zohori Construction and Road Building Co...     Company
...                                                 ...         ...
9994                              Carole Blestel-Feffer      Person
9995                                        Amos, Aston      Person
9996                                 Heri Magnason Arge      Person
9997                                        Neo Hossain      Person
9998                                    Jwala Rambarran      Person

[9999 rows x 2 columns]

In [ ]:
df2

       SURNAME   RANK FREQUENCY (COUNT)
0        SMITH      1         2,442,977
1      JOHNSON      2         1,932,812
2     WILLIAMS      3         1,625,252
3        BROWN      4         1,437,026
4        JONES      5         1,425,470
..         ...    ...               ...
995       ODOM    996            35,020
996  DAUGHERTY    997            34,987
997     TRAVIS    998            34,985
998       TANG    999            34,961
999     ARCHER  1,000            34,949

[1000 rows x 3 columns]

In [ ]:
df_name=df2["SURNAME"]
df_name

0          SMITH
1        JOHNSON
2       WILLIAMS
3          BROWN
4          JONES
         ...
995         ODOM
996    DAUGHERTY
997       TRAVIS
998         TANG
999       ARCHER
Name: SURNAME, Length: 1000, dtype: object

In [ ]:
df_name.sample(10)

661        ATKINS
545         BROCK
371          BUSH
766      JACOBSON
885       SAMPSON
210    CUNNINGHAM
620       RANDALL
982        MCCANN
962      ANDERSEN
3           BROWN
Name: SURNAME, dtype: object

In [ ]:
df_name['lower_case_names'] = df_name.apply(lambda x: x.lower())

In [ ]:
df_name['lower_case_names']

0          smith
1        johnson
2       williams
3          brown
4          jones
         ...
995         odom
996    daugherty
997       travis
998         tang
999       archer
Name: SURNAME, Length: 1000, dtype: object

In [ ]:
names_list = df_name['lower_case_names'].tolist()
#changes to a list

In [ ]:
names_list[1:30]

['johnson',
 'williams',
 'brown',
 'jones',
 'garcia',
 'miller',
 'davis',
 'rodriguez',
 'martinez',
 'hernandez',
 'lopez',
 'gonzalez',
 'wilson',
 'anderson',
 'thomas',
 'taylor',
 'moore',
 'jackson',
 'martin',
 'lee',
 'perez',
 'thompson',
 'white',
 'harris',
 'sanchez',
 'clark',
 'ramirez',
 'lewis',
 'robinson']

In [ ]:
df['has_last_person_name'] = df['Entity Name'].apply(lambda x:  0 if any(substring in x for substring in names_list) else 1)

In [ ]:
df['has_last_person_name'].value_counts()

1    7754
0    2245
Name: has_last_person_name, dtype: int64

In [ ]:
last_name = (df["has_last_person_name"] == 0)
df_last_name = df[last_name]
df_last_name.sample(40)

,Entity Name,Entity Type,has_last_person_name
1134,Centro Cultural de Escuintla “Lic. Aristides C...,Company,0
1808,Javna ustanova Dom za doenchinja i mali deca B...,Company,0
1222,Beijing State-Owned Assets Management (Hong Kong),Company,0
2862,Electronic Banking Services,Company,0
375,Nova tvornica prečistača a.d. Rogatica,Company,0
6594,"Amores Hernández, Julio César",Person,0
1803,Javna zdravstvena ustanova Centar za javno zdr...,Company,0
4350,James Williams,Person,0
1232,Apple Daily,Company,0
5476,"Correia Paiva, António Pedro D. Silva",Person,0
2356,"Buttonwood, LLC",Company,0
8313,Evelina Gudzinskaitė,Person,0
6851,"Charles, Kirkland",Person,0
1208,Bradley Hill Holdings Limited,Company,0
299,Oracle Stone Ltd (Grandtrade),Company,0
7187,Gustavo Efrain Castillo Jaramillo,Person,0
7548,Ali Aşlık,Person,0
9368,Kevin Larry Campbell,Person,0
6176,"Dolama, Virginie Euphrasie",Person,0
9832,Elijah William Modale John Legwaila,Person,0
8035,"Dalleau, Didier",Person,0
2683,Preduzeće za izvodjenje građevinskih radova i ...,Company,0
53,Société Nationale des Tabacs et Allumettes,Company,0
8882,"Khoza, Poppy",Person,0
3162,The Volunteer Arms Southport Ltd,Company,0
2310,Pak Muzaffar Cables,Company,0
965,Porvoon A-asunnot,Company,0
1632,Electricite du Laos,Company,0
899,Los Brothers,Company,0
6107,"Minchev, Mincho Genchev",Person,0
2088,Palai Mon (pale Mon),Company,0
4612,"Polledo Mesa, Lázaro Leslie",Person,0
143,Schienen-Control Österreichische Gesellschaft ...,Company,0
9540,"Pae, Won Chol",Person,0
2049,Maroc Telecom S.A.,Company,0
1682,Barclayville Health Center,Company,0
5879,"Ashlewi, Abdulfattah Khalifa Arwag",Person,0
8783,Manuel Sanchez Gonzalez,Person,0
2180,Nelson Civic Choir,Company,0
7185,Emílio Guadalupe Fernandes Lima,Person,0

In [ ]:
derf hasName(entity):
	e = entity.lower()
	for n in names_list:
		if n in e:
			retunr True
	returnn false

In [ ]:
df.sample(10)

,Entity Name,Entity Type,has_common_person_name
2624,Land Transport Authority (LTA),Company,1
4047,سیف ال فرقان,Company,1
5294,"Nehemia, Abraham",Person,1
337,Argo Group International Holdings Ltd.,Company,1
5945,Chloe White,Person,1
3345,CMED Fuels,Company,1
470,Svay Rieng University,Company,1
2158,Nissan International Holding B.V.,Company,1
1611,OsOO Kyrgyzskaya Federatsiya professionalnogo ...,Company,1
5332,"Ahmad, Nabeel",Person,1

In [ ]:
pip install pycountry

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pycountry
  Downloading pycountry-22.3.5.tar.gz (10.1 MB)
     |████████████████████████████████| 10.1 MB 5.1 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from pycountry) (57.4.0)
Building wheels for collected packages: pycountry
  Building wheel for pycountry (PEP 517) ... done
  Created wheel for pycountry: filename=pycountry-22.3.5-py2.py3-none-any.whl size=10681845 sha256=d34054ad26be11d2a7a953c2a83e97198283adaea6d9d5bfbcc0aa742f8d5ac2
  Stored in directory: /root/.cache/pip/wheels/0e/06/e8/7ee176e95ea9a8a8c3b3afcb1869f20adbd42413d4611c6eb4
Successfully built pycountry
Installing collected packages: pycountry
Successfully installed pycountry-22.3.5

In [ ]:
import nltk
nltk.download('crubadan')
nltk.download('punkt')
import pycountry
from nltk.stem import SnowballStemmer

[nltk_data] Downloading package crubadan to /root/nltk_data...
[nltk_data]   Package crubadan is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [ ]:
def ad_col():
  subprocess.check_call([sys.executable, "-m", "pip", "install", "alphabet-detector"])
  from alphabet_detector import AlphabetDetector
  ad = AlphabetDetector()
  df['langs_ad'] = df['Entity Name'].apply(lambda x: [ad.detect_alphabet(x)])
  df['langs_ad'] = df['langs_ad'].str[0]
  df['langs_ad'] = [list(e) for e in df.langs_ad]
  df['langs_ad'] = df['langs_ad'].str[0]

In [ ]:
ad_col()

In [ ]:
df.sample(10)

,Entity Name,Entity Type,has_common_person_name
633,CFAO,Company,1
8966,"Dupraz, Christian",Person,1
8069,"TÜRKMENOĞLU,Mehmet",Person,1
3949,JAVNO KOMUNALNO PREDUZEĆE GRADSKA TOPLANA PIROT,Company,1
9946,"Pate, Oa Lillian",Person,0
6261,Sanjay Debnath,Person,1
6062,Nick Bozikis,Person,1
6831,Yaroslav Mikhaylovich Shvyryaev,Person,1
7793,"Lopes dos Reis Monteiro, Júlio",Person,1
6385,"Zibula, Litha Law",Person,0

list1 = ["Michael", "Ali", "David", "Mohamed", "John", "Mohammed", "Ahmed","Abdul", "Thomas", "Juan", "James","Joseph","Carlos",
         "Abdullah", "Antonio", "Robert", "Richard", "Peter", "王", "李", "张", "刘", "陈",
         "杨", "黄", "赵", "مُ", "Emma", "Maria", "Nushi", "Jose", "Wei", "Yan", "Li" , "Smith", 
         "Ana", "Ying", "Juan", "Anna","Mary" "Jean", "Robert", "Daniel" , "Luis", 
         "Carlos", "James", "Antonio", "Joseph", "Hui", "Elena", "Francisco","Hong"
         "Marie", "Min ", "Lei" ,"Yu","Ibrahim", "Peter", "Fatima", "Aleksandr", 
         "Richard", "Xin", "Ping","Paul", "Lin ", "Olga", "Sri", "Pedro", "William", "Rosa", "Thomas", 
         "Jorge", "Yong", "Elizabeth", "Sergey", "Ram", "Patricia", "Hassan", "Anita","Manuel","Victor", "Sandra",
         "Ming", "沐宸", "浩宇", "沐辰", "茗泽", "奕辰", "宇泽", "浩然", "奕泽","宇轩", "沐阳", 
         "若汐", "一诺", "艺涵","依诺", "梓涵", "苡沫", "雨桐", "欣怡", "语桐", "语汐" ,"Hossain","佐藤", "鈴木","高橋"
         "田中", "渡辺", "伊藤","中村", "小林", "山本", "加藤" , "吉田", "山田", "山口","松本", "	井上", "木村", "清水", "林",
         "斉藤", "斎藤", "山崎", "中島", "森"	, "阿部", "池田", "橋本", "石川", "	山下", "小川", "石井", "後藤", "岡田"]

In [ ]:

list1 = ["Michael", "Ali", "David", "Mohamed", "John", "Mohammed", "Ahmed","Abdul", "Thomas", "Juan", "James","Joseph","Carlos",
         "Abdullah", "Antonio", "Robert", "Richard", "Peter", "王", "李", "张", "刘", "陈",
         "杨", "黄", "赵", "مُ", "Emma", "Maria", "Nushi", "Jose", "Wei", "Yan", "Li" , "Smith", 
         "Ana", "Ying", "Juan", "Anna","Mary" "Jean", "Robert", "Daniel" , "Luis", 
         "Carlos", "James", "Antonio", "Joseph", "Hui", "Elena", "Francisco","Hong"
         "Marie", "Min ", "Lei" ,"Yu","Ibrahim", "Peter", "Fatima", "Aleksandr", 
         "Richard", "Xin", "Ping","Paul", "Lin ", "Olga", "Sri", "Pedro", "William", "Rosa", "Thomas", 
         "Jorge", "Yong", "Elizabeth", "Sergey", "Ram", "Patricia", "Hassan", "Anita","Manuel","Victor", "Sandra",
         "Ming", "沐宸", "浩宇", "沐辰", "茗泽", "奕辰", "宇泽", "浩然", "奕泽","宇轩", "沐阳", 
         "若汐", "一诺", "艺涵","依诺", "梓涵", "苡沫", "雨桐", "欣怡", "语桐", "语汐" ,"Hossain","佐藤", "鈴木","高橋"
         "田中", "渡辺", "伊藤","中村", "小林", "山本", "加藤" , "吉田", "山田", "山口","松本", "	井上", "木村", "清水", "林",
         "斉藤", "斎藤", "山崎", "中島", "森"	, "阿部", "池田", "橋本", "石川", "	山下", "小川", "石井", "後藤", "岡田",
         "Smith", "Johnson", "Williams", "Brown", "Jones", "Miller","Davis", "Garcia" , "Rodriguez"
        "Wilson", "Martinez", "Anderson", "Taylor","Thomas", "Hernandez", "Moore", "Martin", "Jackson", "Thompson", "Lopez", "Lee", "Gonzalez", 
        "Harris", "Lewis", "Robinson", "Perez", "José", "María", "Marry", "Lucía", "Sofía", "Martina"
        "Paula", "Lucas", "Hugo", "Martín", "Daniel", "Pablo", "ария","Маша" , "Анна", "Аня", "Виктория", "Вика", "Ольга" ,"Оля", 
         "Наталья", "Наташа", "Татьяна" "Таня","Иван" "Ваня", "Дмитрий" "Дима", "Пётр","Владимир" ,"Николай", "Коля", "Антон", "Андрей", 
         "Krishna", "Shiva", "Narayan", "Piyush", "Vishwajeet", "Arjuna", "Hariom", "Karan", "Pavan", "Aditya", "Vihaan", "Pranav", "Rithvik", "Aarush",
         "حسن", "مُحَمَّد", "بن", "محمد", "خالد", "عبدالله","أحمد", "فهد","سلمان", "سعود	" ,"Mr", "Jr", "Mrs","Esq","Phd", "先生", 'Ali','Ali','John','David','Li','Abdul','Ana','Ying','Michael',
         'Juan','Anna','Mary','Jean','Robert','Daniel','Luis','Carlos','James','Antonio','Joseph']
list2=["State"]



df['has_common_person_name'] = df['Entity Name'].apply(lambda x:  0 if any(substring in x for substring in list1) else 1)

#for Japanese the the list of accurate but the the Company that are calsifed wrong have parentheses, so the punctuation function will help with that, also for chinese

In [ ]:
df

,Entity Name,Entity Type,has_place_name,has_common_person_name,has_common_name,has_prefix/suffix
0,Habib Afghan Road and Construction Company,Company,0,1,1,1
1,Aziz Construction Company,Company,0,1,1,1
2,Musawir Najib Ltd,Company,1,1,1,1
3,Bamyan Central Hospital,Company,1,1,0,1
4,Sadat Zohori Construction and Road Building Co...,Company,0,1,0,1
...,...,...,...,...,...,...
9994,Carole Blestel-Feffer,Person,0,1,1,1
9995,"Amos, Aston",Person,1,1,0,1
9996,Heri Magnason Arge,Person,1,1,0,1
9997,Neo Hossain,Person,1,0,0,1
9998,Jwala Rambarran,Person,0,0,1,1

In [ ]:
df['has_common_person_name'].value_counts()

1    8168
0    1831
Name: has_common_person_name, dtype: int64

In [ ]:
common_name = (df["has_common_person_name"] == 0)
df_common_name = df[common_name]
df_common_name.sample(40)

,Entity Name,Entity Type,has_place_name,has_common_person_name,has_common_name,has_prefix/suffix
9977,Krishna Jhugroo,Person,0,0,1,1
7934,Ramiz Firudin Oğlu Tahirov,Person,0,0,1,1
7272,لبنى بنت خالد بن سلطان القاسمي,Person,0,0,0,1
8298,Robert K. Dickson,Person,0,0,1,1
4480,بنسي ليبرمان,Person,0,0,0,1
8051,佐藤一貴,Person,0,0,0,1
5170,Eko Yuli Irawan,Person,1,0,1,1
2381,PacWealth Capital Limited,Company,1,0,1,1
8290,王佳哲,Person,0,0,0,1
7452,"Abdel Hamid, Emad Eddin Ahmed Mahmoud",Person,0,0,1,1
7915,李兆雄,Person,0,0,0,1
4693,"Al Zawaydeh, Awwad Mohammed Salman",Person,0,0,1,1
3042,National Flour Mills Limited,Company,0,0,1,1
9399,"Hollabaugh, Richard",Person,1,0,1,1
7899,بكر بن محمد بن عوض بن لادن,Person,0,0,0,1
1225,"Yingsheng Financial Investment Management Co.,...",Company,1,0,1,1
7999,张辉,Person,0,0,0,1
6971,Richard Davis,Person,1,0,1,1
8943,Michael Hickey,Person,0,0,1,1
4962,Luis Hernandez Echavez,Person,0,0,1,1
4764,黄志祥,Person,0,0,0,1
3792,Front Popolari għal-Liberazzjoni tal-Palestina...,Company,1,0,1,1
7064,Leyre Martín Adalia,Person,1,0,0,1
7389,Josefa Joana Rebeca Cangombe,Person,1,0,1,1
5475,"Browne, Michael Eesa Amery",Person,0,0,1,1
5728,Ahmed Vall Ould Saleh,Person,1,0,1,1
9796,"Aristizábal Ramírez, Juan Mauricio",Person,0,0,1,1
7752,刘啟群,Person,0,0,0,1
2711,Denver Trading Limited,Company,1,0,1,1
9634,Ahmed Soliman Ahmed Ibrahim Shouail,Person,1,0,1,1
5369,陈祝全,Person,0,0,0,1
6673,Zaiyong Li,Person,0,0,1,1
4733,"Hamilton, Michael",Person,1,0,1,1
9195,Juan Bordes Aznar,Person,1,0,1,1
4898,"Ahmed, Nishan",Person,1,0,1,1
7855,Karen Anderson,Person,1,0,1,1
9201,李向东,Person,0,0,0,1
9617,"Mahammed, Abdallah Ali",Person,0,0,1,1
9638,"Valverde Aguino, Hugo Felipe",Person,1,0,1,1
7741,Mohammad Ali Sabah Abdol Mohsen,Person,0,0,1,1

In [ ]:
common_nameCGK = ((df["has_common_person_name"] == 0) & (df["langs_ad"]=="CJK")	)
df_common_nameCGK = df[common_nameCGK]
df_common_nameCGK.sample(10)

KeyError: ignored

In [ ]:
common_nameDEVANAGARI = ((df["has_common_person_name"] == 0) & (df["langs_ad"]=="ARABIC")	)
df_common_nameDEVANAGARI = df[common_nameDEVANAGARI]
df_common_nameDEVANAGARI.sample(30)

,Entity Name,Entity Type,langs_ad,has_common_person_name
6766,عبدالله بن إبراهيم العياضي,Person,ARABIC,0
5847,عبدالله بن إبراهيم العياضي,Person,ARABIC,0
9666,عبدالله بن محمد العيسى,Person,ARABIC,0
8357,عبدالله بن محمد العيسى,Person,ARABIC,0
6494,بكر بن محمد بن عوض بن لادن,Person,ARABIC,0
5988,محمد بن راشد آل مكتوم,Person,ARABIC,0
9894,خالد بن عبد العزيز الفالح,Person,ARABIC,0
8188,عبد القادر جله محمد,Person,ARABIC,0
9820,أحمد بن فهد بن سلمان بن عبد العزيز آل سعود,Person,ARABIC,0
6174,طارق محمد زكي,Person,ARABIC,0
6642,أمين بن حسن الناصر,Person,ARABIC,0
6975,محمد بن حمد بن محمد الشرقي,Person,ARABIC,0
4897,صالح بن ناصر الجاسر,Person,ARABIC,0
5865,عبدالله بن إبراهيم العياضي,Person,ARABIC,0
9673,عبدالله بن محمد العيسى,Person,ARABIC,0
9307,أمين بن حسن الناصر,Person,ARABIC,0
5696,أمين بن حسن الناصر,Person,ARABIC,0
9408,عبدالله بن محمد العيسى,Person,ARABIC,0
4361,محمد یعقوب,Person,ARABIC,0
8111,بكر بن محمد بن عوض بن لادن,Person,ARABIC,0
4530,خالد بن عبد العزيز الفالح,Person,ARABIC,0
8847,خالد بن عبد العزيز الفالح,Person,ARABIC,0
5866,محمد إدعمار,Person,ARABIC,0
8986,حياة طعاطي بنت مزيان,Person,ARABIC,0
7272,لبنى بنت خالد بن سلطان القاسمي,Person,ARABIC,0
6331,عبدالله بن محمد العيسى,Person,ARABIC,0
3353,الجزيرة بنغازي,Company,ARABIC,0
8812,خالد بن عبد العزيز الفالح,Person,ARABIC,0
6839,أحمد بن فهد بن سلمان بن عبد العزيز آل سعود,Person,ARABIC,0
6617,غادة م حسن الأشقر,Person,ARABIC,0

In [ ]:
common_name3 = ((df["Entity Type"] == "Person") & (df["langs_ad"]=="CJK")	)
df_common_name3 = df[common_name3]
df_common_name3.sample(30)

KeyError: ignored

In [ ]:

list2=["Mr", "Jr", "Mrs","Esq","Phd", "先生"]

df['has_prefix/suffix'] = df['Entity Name'].apply(lambda x:  0 if any(substring in x for substring in list2) else 1)

In [ ]:
df['has_prefix/suffix'].value_counts()

1    9987
0      12
Name: has_prefix/suffix, dtype: int64

In [ ]:
prefix_suffix = (df["has_prefix/suffix"] == 0)
df_prefix_suffix = df[prefix_suffix]
df_prefix_suffix.sample(12)

,Entity Name,Entity Type,has_common_person_name,has_prefix/suffix
7120,"Leo I. Higdon, Jr",Person,1,0
7708,"Mrabet, Mohamed Hefdhi",Person,0,0
4312,Manuel Amadeo Esquivel,Person,1,0
4792,Lawrence Lual Malong Yor Jr,Person,1,0
5618,Adolfo Feracin Jr,Person,1,0
6292,Jakaya Mrisho Kikwete,Person,1,0
8974,"Mršić, Zdravko",Person,1,0
9868,Ali Mroudjaé,Person,0,0
5583,William F. Gifford Jr.,Person,1,0
8753,Karol Mrva,Person,1,0
7914,"Mruttu, John Mtuta",Person,0,0
5815,Mr Morgan Sheehy,Person,1,0

**https://pypi.org/project/pycountry/**

In [ ]:
import pycountry

In [ ]:
list(pycountry.countries)[0]

Country(alpha_2='AW', alpha_3='ABW', flag='🇦🇼', name='Aruba', numeric='533')

In [ ]:
df[place_name]=country.name

NameError: ignored